# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureFileCopy@4
- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(agent.builddirectory)'
    azureSubscription: 'Synapse_BLR_Team_DevTest_01(16620d54-d71c-4d22-910b-e711ca35efc6)'
    Destination: 'AzureBlob'
    storage: 'praveensg2'
    ContainerName: 'praveensg2'
